### PR TITLE
Updated CureDAO presentation (includes compensation plan)

### PR DESCRIPTION
**Pull request by sajustsmile**
CureDAO presentation 2.0 Draft is complete.

### CODE REVIEW

**Review by agelesspartners — APPROVED** [review]
Looks good, thanks Sandra!

**Review by mikepsinn — APPROVED** [review]

**Comment by AMelhede** [comment]
Wonderful job on it, Sandra! So much valuable and inspiring information in there!

I have a few suggestions on top of Vincenzo's:
Slide 10:
It might be more succinct to say, "Nearly all apps show you what you have done rather than what you should do to prevent or treat disease.​"

Slide 11: 
It would likely look more professional if we made the screenshots a bit bigger and clearer.

Slide 15:
Under the section: "OpenCures Assays & Biobanking"
We might want to change it to:
"You should own your health data. We let you own your samples and provide access to assays like metabolomics and proteomics, which are currently only available to researchers."

Under the section: "OpenCures Trial Management"
We might want to change it to:
"We serve organizations with all the tools and automations to manage participants, their health data, and workflows for their clinical products."

Slide 27:
It might be critical to mention that the market is rapidly expanding.
I.e. The potential market is much bigger than just 613 million people.

Slide 29:
How do we measure DAO members? We currently have 65 in Discord, but I guess we can't say that all are a part of the DAO? Possibly only contributors are. Otherwise, we could call it something else.

Slide 30:
- "Build community, social media content​" could be re-phrased into "Build community & social media content"
- "Take newly developed interventions​" could be re-phrased into "Use newly developed interventions"
- The section, "Educate loved ones about longer health-span." Could be rephrased into "Educate loved ones about healthier lives"

**Comment by sajustsmile** [comment]
Slide 11: If I can get access to the original location of these specific slides I could download them (these were copied and pasted from previous .ppt) Also this is the largest they could get in order to fit all three on one slide, if its fine with ya'll "larger" could be - one slide on one .ppt (that's 3 extra slides...adding onto the number of slides).

Slide 27: So what is the final suggestion here? What should replace the current content in this section?

Slide 29: Have we come to a conclusion on what  the something else" is ?

Let me know the confirmed finalized changes and I'll make the updates accordingly.

**Comment by AMelhede** [comment]
Thank you, Sandra! I appreciate it!

@mikepsinn or @vincenzodomina, can you help Sandra get the slides, so she can edit them?

In terms of slide, 27, I like the current number of 613 million people. I simply would love for there to also be a point on the potential of the market, which is much bigger than just 613 million.

Slide 29, what are your thoughts on the measurements of DAO members, Vincenzo, and Mike?

**Comment by sajustsmile** [comment]
@AMelhede Added adjustments to the content, please have a quick look so we can "finalize" this deck?

**Comment by AMelhede** [comment]
Thank you for doing this, Sandra!

I love the changes.
I made a few edits also.

On slide 27:
It might be critical to mention that the market is rapidly expanding. I.e. The "total addressable market" is much bigger than just 613 million people.
That is one of the reasons why I see a greater potential in CureDAO than any other Health DAO out there.
What are your thoughts, @mikepsinn & @vincenzodomina?

**Comment by Taliskermalt** [comment]
Looks good!

**Pull request merged**
